import {
  ENDPOINT_POST_ALL_COIN,
  ENDPOINT_POST_PUT_UPDATE_COIN,
} from "../../constants/endpoint";
import SearchHigherComponent from "../../components/SearchHigherComponent";
import { Filter } from "../../settings";

const columns = [
  {
    key: "coin",
    label: "Asset",
    isDefault: true,
  },
  {
    key: "network",
    label: "Network",
  },
  {
    key: "hotWalletBalance",
    label: "Hot wallet",
    isHotWallet: true,
  },
  {
    key: "enable",
    label: "Active",
    isBool: true,
  },
  {
    key: "depositEnable",
    label: "Deposit",
    isBool: true,
  },
  {
    key: "transferEnable",
    label: "Transfer",
    isBool: true,
    isTransfer: true,
  },
  {
    key: "withdrawEnable",
    label: "Withdraw",
    isBool: true,
  },
];

export default SearchHigherComponent({
  endpoint: ENDPOINT_POST_ALL_COIN,
  title: "Coin list",
  columns,
  updateEndpoint: ENDPOINT_POST_PUT_UPDATE_COIN,
  createFields: [
    new Filter({
      key: "coin",
      type: "input",
      text: "Coin",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "network",
      type: "input",
      text: "Network",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "fullName",
      type: "input",
      text: "Full name",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "hasAddressTag",
      type: "singleCheckbox",
      text: "Has address tag",
      col: 12,
    }),
    new Filter({
      key: "withdrawEnable",
      type: "singleCheckbox",
      text: "Withdraw enable",
      col: 12,
    }),
    new Filter({
      key: "withdrawFee",
      type: "input",
      text: "Withdraw fee",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "minimumWithdraw",
      type: "input",
      text: "Minimum withdraw",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "depositEnable",
      type: "singleCheckbox",
      text: "Deposit enable",
      col: 12,
    }),
    new Filter({
      key: "transferEnable",
      type: "singleCheckbox",
      text: "Transfer enable",
      col: 12,
    }),
    new Filter({
      key: "transferFee",
      type: "input",
      text: "Transfer fee",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "minimumTransfer",
      type: "input",
      text: "Minimum transfer",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "enable",
      type: "singleCheckbox",
      text: "Active asset",
      col: 12,
    }),
    new Filter({
      key: "isFixedPrice",
      type: "singleCheckbox",
      text: "Is fixed price",
      col: 12,
    }),
    new Filter({
      key: "usdPrice",
      type: "input",
      text: "USD price",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "isDefault",
      type: "singleCheckbox",
      text: "Is default",
      col: 12,
      require: true,
    }),
  ],
  updateFields: [
    new Filter({
      key: "coin",
      type: "input",
      text: "Coin",
      col: 12,
      require: true,
      disabled: true,
    }),
    new Filter({
      key: "network",
      type: "input",
      text: "Network",
      col: 12,
      require: true,
      disabled: true,
    }),
    new Filter({
      key: "fullName",
      type: "input",
      text: "Full name",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "hasAddressTag",
      type: "singleCheckbox",
      text: "Has address tag",
      col: 12,
    }),
    new Filter({
      key: "withdrawEnable",
      type: "singleCheckbox",
      text: "Withdraw enable",
      col: 12,
    }),
    new Filter({
      key: "withdrawFee",
      type: "input",
      text: "Withdraw fee",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "minimumWithdraw",
      type: "input",
      text: "Minimum withdraw",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "depositEnable",
      type: "singleCheckbox",
      text: "Deposit enable",
      col: 12,
    }),
    new Filter({
      key: "transferEnable",
      type: "singleCheckbox",
      text: "Transfer enable",
      col: 12,
    }),
    new Filter({
      key: "transferFee",
      type: "input",
      text: "Transfer fee",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "minimumTransfer",
      type: "input",
      text: "Minimum transfer",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "enable",
      type: "singleCheckbox",
      text: "Active asset",
      col: 12,
    }),
    new Filter({
      key: "isFixedPrice",
      type: "singleCheckbox",
      text: "Is fixed price",
      col: 12,
    }),
    new Filter({
      key: "usdPrice",
      type: "input",
      text: "USD price",
      col: 12,
      require: true,
    }),
    new Filter({
      key: "isDefault",
      type: "singleCheckbox",
      text: "Is default",
      col: 12,
      require: true,
    }),
  ],
  updateBy: "coin",
});
